version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "vpavlov-me"
    labels:
      - "dependencies"
      - "automated-pr"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "vpavlov-me"
    labels:
      - "dependencies"
      - "automated-pr"
