name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - feature
      - enhancement
      - feat
  - title: "🐛 Fixes"
    labels:
      - bug
      - fix
      - hotfix
  - title: "🧰 Maintenance"
    labels:
      - chore
      - ci
      - dependencies
      - refactor
  - title: "🧪 Tests"
    labels:
      - test
      - tests
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
template: |
  ## Что нового

  $CHANGES

  ---

  _Сгенерировано автоматически Release Drafter._
