# SwiftLint Configuration for Bloomly

# Paths to include during linting
included:
  - App
  - Packages

# Paths to exclude during linting
excluded:
  - .build
  - .swiftpm
  - DerivedData
  - Pods
  - vendor
  - "**/Generated"
  - "**/.build"

# Opt-in rules to enable
opt_in_rules:
  - attributes
  - closure_spacing
  - fatal_error_message
  - array_init
  - closure_end_indentation
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - last_where
  - modifier_order
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Rules to disable
disabled_rules:
  - todo
  - trailing_comma

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 40
  error: 60

file_length:
  warning: 400
  error: 600
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 15
  ignores_case_statements: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - db
    - x
    - y
    - z
  allowed_symbols:
    - _

type_name:
  min_length: 3
  max_length: 50

function_parameter_count:
  warning: 5
  error: 8

reporter: "xcode"
