name: Actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/**"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
          fail_on_error: true
