name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: ios
            scheme: BabyTrack
            destination: 'platform=iOS Simulator,name=iPhone 15'
            action: test
          - name: watchos
            scheme: BabyTrackWatch
            destination: 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)'
            action: build
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.app
      OTHER_SWIFT_FLAGS: -warnings-as-errors
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s "$DEVELOPER_DIR"
      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
      - name: Install Tuist
        run: |
          if ! command -v tuist >/dev/null 2>&1; then
            curl -Ls https://install.tuist.io | bash
          fi
      - name: Install xcpretty
        run: |
          gem install xcpretty --no-document
      - name: Generate Workspace
        run: |
          export PATH="$HOME/.tuist/bin:$PATH"
          tuist generate --path .
      - name: ${{ matrix.target.name }} ${{ matrix.target.action }}
        run: |
          xcodebuild -workspace BabyTrack.xcworkspace \
            -scheme "${{ matrix.target.scheme }}" \
            -destination "${{ matrix.target.destination }}" \
            -parallelizeTargets \
            -skipPackagePluginValidation \
            ${{ matrix.target.action }} | xcpretty
